---
branches:
  only:
    - main
cache:
  directories:
    - "node_modules"
install:
  - yarn install --ignore-platform
language: node_js
node_js:
  - "lts/*"
notifications:
  webhooks: []
sudo: false
